name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 0.8.0
homepage: https://github.com/brianegan/chewie
author: Lommi <lommi@lommi.is>

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  open_iconic_flutter: ">=0.3.0 <0.4.0"
  video_player: ">=0.7.0 <0.8.0"
  screen: ">=0.0.4 <0.1.0"

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
